// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type State struct {
	ID         int64
	AliasCount int64
}

type Url struct {
	ID    int64
	Alias string
	Url   string
}
