// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: state.sql

package database

import (
	"context"
)

const loadState = `-- name: LoadState :one
SELECT alias_count FROM state
WHERE id = 1
`

func (q *Queries) LoadState(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, loadState)
	var alias_count int64
	err := row.Scan(&alias_count)
	return alias_count, err
}

const storeState = `-- name: StoreState :exec
UPDATE state
SET alias_count = ?
WHERE id = 1
`

func (q *Queries) StoreState(ctx context.Context, aliasCount int64) error {
	_, err := q.db.ExecContext(ctx, storeState, aliasCount)
	return err
}
